name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build_windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: |
          cmake --version
          cmake `
            -B build `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=0e5b6991-d74f-4b3d-a41c-cf096e0b2508
          cmake --build build

      - name: Test
        run: ctest --test-dir build

  build_macos:
    name: Build and Test on MacOS
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        env:
          MACOSX_DEPLOYMENT_TARGET: 15.0
          ARCHFLAGS: "-arch arm64"
        run: |
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_C_COMPILER=$(brew --prefix llvm@18)/bin/clang \
            -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@18)/bin/clang++ \
            -DCMAKE_CXX_COMPILER_ID_ARG1=-resource-dir=$(brew --prefix llvm@18)/lib/c++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=0e5b6991-d74f-4b3d-a41c-cf096e0b2508
          cmake --build build

      - name: Test
        run: ctest --test-dir build

  build_linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Toolchain
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S cmake ninja

      - name: Build
        run: |
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=d0edc3af-4c50-42ea-a356-e2862fe7a444
          cmake --build build

      - name: Test
        run: ctest --test-dir build
